
### Get All Users (Protected Route)
GET http://localhost:3000/users/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyMzQiLCJzdWIiOjQsImlhdCI6MTczMDA0MjU5MywiZXhwIjoxNzMwMDc4NTkzfQ.XplVWJkF3ZxRw7cb4MXFDiAdx7nWqWUy-F4GT3hzvcw.eyJlbWFpbCI6IjEyMyIsInN1YiI6MSwiaWF0IjoxNzMwMDQyNTE0LCJleHAiOjE3MzAwNzg1MTR9.AZtMn5D4nH4XVd8RzNa-WKXw96ad1cIMc2Uaskmm7CU.eyJlbWFpbCI6IjEyMyIsInN1YiI6MywiaWF0IjoxNzMwMDM4MzQwLCJleHAiOjE3MzAwNzQzNDB9.iI9uejJq_YNvYsPqEOn0JRmWW5u_OvJX_DUQMwodBv8